kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ui-ceshi
rules:
- apiGroups:
  - ""
  resources:
  - services
  - services/proxy
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ui-ceshi-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ui-ceshi
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ceshi
