---
apiVersion: v1
kind: Pod
metadata:
  name: mytls
  labels:
    app: mytls
spec:
  containers:
  - name: mytls
    image: ikubernetes/myapp:v1
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: tls
      mountPath: /usr/nginx
  volumes:
  - name: tls
    secret:
      secretName: mytls 

