---
apiVersion: v1
data:
  nginx_port: ODAwMAo=
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
---
apiVersion: v1
kind: Pod
metadata:
  name: mysecret
  labels:
    app: mysecret
spec:
  containers:
  - name: mysecret
    image: ikubernetes/myapp:v1
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: http
      mountPath: /usr/nginx
  volumes:
  - name: http
    secret:
      secretName: mysecret
---
