apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:0810
        ports:
        - containerPort: 80


  # 扩容 kubectl scale deployment nginx-deployment --replicas 10
  # 如果集群支持 horizontal pod autoscaling 的话，还可以为Deployment设置自动扩展：

# kubectl autoscale deployment nginx-deployment --min=10 --max=15 --cpu-percent=80
# 更新镜像：kubectl set image deployment/nginx-deployment nginx=nginx:1.9.1
# 回滚：kubectl rollout undo deployment/nginx-deployment
# 暂停deployment： kubectl rollout pause deployment/nginx-deployment
