apiVersion: v1
kind: Pod
metadata:
  name: pv-hostpath
  namespace: default
  labels:
    app: pv-hostpath
spec:
  containers:
  - name: pv-hostpath
    image: ikubernetes/myapp:v1
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /use/share/nginx/html/
  volumes:
  - name: html
    hostPath:
      path: /data/test
      type: DirectoryOrCreate
