apiVersion: v1
kind: Pod
metadata:
  name: pv-nfs
  namespace: default
  labels:
    app: pv-nfs
spec:
  containers:
  - name: pv-nfs
    image: ikubernetes/myapp:v1
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /use/share/nginx/html/
  volumes:
  - name: html
    nfs:
      path: /data/v1
      server: 192.168.29.103
