kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim1
  namespace: router
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: managed-nfs-storage
